config/routes.rb
Rails.application.routes.draw do

    get 'tags/:tag', to: 'caps#index', as: :tag

    get 'caps/index'
    get 'caps/show'
    get 'caps/new'
    get 'caps/edit'

    resources :caps, param: :token do
      resources :participations
    end
    resources :password_resets
    resources :users, param: :token
    resources :searches

    resources :sessions, only: [:new, :create, :destroy]

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'user/index'
    get 'new_cap/index'
    root 'new_cap#index'

    resources :users do
        member do
            get :confirm_email
        end
    end

end

app/controllers/new_cap_controller.rb
class NewCapController < ApplicationController
  def index
    @user = User.new
    @news = Cap.limit(4).order('start_at desc')
  end
end

app/helpers/new_cap_helper.rb
module NewCapHelper
end

app/views/new_cap/contato.html.erb
<div class="row">
  <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
    <h1>Contato</h1>
    <h3>Nos dê a oportunidade de tirar suas dúvidas</h3>
      <h3>Não seja tímido!</h3>
  </div>
</div>
<div class="contact-form wow fadeIn" data-wow-duration="1000ms" data-wow-delay="600ms">
  <div class="row">
    <div class="col-sm-6">
      <form id="main-contact-form" name="contact-form" method="post" action="#">
        <div class="row  wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
          <div class="col-sm-6">
            <div class="form-group">
              <input name="name" class="form-control" placeholder="Nome" required="required">
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <input type="email" name="email" class="form-control" placeholder="Endereço de Email" required="required">
            </div>
          </div>
        </div>
        <div class="form-group">
          <input name="subject" class="form-control" placeholder="Assunto" required="required">
        </div>
        <div class="form-group">
          <textarea name="message" id="message" class="form-control" rows="4" placeholder="Escreva sua mensagem" required="required"></textarea>
        </div>
        <div class="form-group">
          <button type="submit" class="btn-submit">Envie agora</button>
        </div>
      </form>
    </div>
    <div class="col-sm-6">
      <div class="contact-info wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
        <p>A newcap está nas redes sociais. Curta nossas páginas e fique por dentro de tudo que acontece na newcap! </p>
        <ul class="address">
          <li><i class="fa fa-map-marker"></i> <span> Endereço:</span> Brasília </li>
          <li><i class="fa fa-phone"></i> <span> Telefone:</span> +55 61 92265142  </li>
          <li><i class="fa fa-envelope"></i> <span> Email:</span><a href="mailto:someone@yoursite.com"> newcap@thenewcap.com</a></li>
          <li><i class="fa fa-globe"></i> <span> Website:</span> <a href="#">www.thenewcap.com</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/new_cap/expositor.html.erb
  <div class="row">
    <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
      <h2>Expositor</h2>
      <h3>Imagine se você pudesse ensinar em qualquer lugar do mundo, sem restrições...</h3>
      <h3>Crie o projeto, escolha o local e faça isso!</h3>
      <p>Faça parte da newcap e ajude a conectar pessoas pelo conhecimento.</p>
      <p>Para ser um Expositor com a newcap você não precisa ser ligado a nenhuma instituição de ensino, possuir certificações e muito menos de uma sala de aula convencional. </p>
    </div>
  </div>
  <div class="blog-posts">
    <div class="row">
      <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">
        <div class="post-thumb">
          <%= image_tag("shutterstock_159632543.jpg", class: 'img-responsive')%>
        </div>
        <div class="entry-header">
          <h3><a href="#">Crie seu cap</a></h3>
        </div>
        <div class="entry-content">
          <p>Crie seu cap de um jeito simples e rápido. Utilize nosso template e recomende materiais de referência e pesquisa, assim os participantes poderão estudar antes.</p>
        </div>
      </div>
      <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
        <div class="post-thumb">
            <%= image_tag("shutterstock_219009229.jpg", class: 'img-responsive')%>
        </div>
        <div class="entry-header">
          <h3><a href="#">Escolha o local</a></h3>
        </div>
        <div class="entry-content">
          <p>Uma sala de aula é o melhor local para aprender? Se for, marque lá. Mas caso não, escolha o lugar que combine melhor com a sua proposta. Um parque, um museu, um café, qualquer lugar que você ache que vá contribuir para a experiência de todos. </p>
        </div>
      </div>
      <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="800ms">
        <div class="post-thumb">
          <%= image_tag("shutterstock_233553616.jpg", class: 'img-responsive')%>
        </div>
        <div class="entry-header">
          <h3><a href="#">Dê o seu preço</a></h3>
        </div>
        <div class="entry-content">
          <p>Tudo tem um preço, e nós sabemos disso. Diga qual é o seu, indique o número mínimo de participantes e diga quanto vai custar para cada um. Mas se seu preço for apenas a experiência de conhecer novas pessoas, marque o campo gratuito. </p>
        </div>
      </div>
    </div>
  </div>

  <div class="team-members">
    <div class="container">
      <div class="row">
        <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
          <h2>Próximos Caps</h2>
          <p>Confira os próximos Caps e participe!</p>
        </div>
      </div>
      <div class="team-members">
        <div class="row">
          <% @news.each do |cap| %>
            <div class="col-sm-3">
              <div class="team-member wow flipInY" data-wow-duration="1000ms" data-wow-delay="500ms">
                <div class="member-image">
                  <%=  image_tag(
                      cap.cap_image_file_name.blank? ? "capdefault" :
                      cap.cap_image.url, alt: cap.title, class: "img-responsive") %>
                </div>
                <div class="member-info">
                  <h3><%= link_to cap.title, cap %></h3>
                  <h4><%= cap.tag_list %></h4>
                  <p>Início: <%= cap.start_at.strftime(" %d/%m/%Y") %> <%= cap.time_start.strftime(" %M:%S") %></p>
                </div>
                <div class="social-icons">
                  <%= link_to 'Participar', new_cap_participation_path(cap) %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/new_cap/home.html.erb
<header id="home">
  <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active" style="background-image: url('/assets/shutterstock_307873628.jpg');">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Bem vindo a <span>newcap</span></h1>
          <p class="animated fadeInRightBig">Conectando pessoas pelo conhecimento</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Entrar</a>
        </div>
      </div>
      <div class="item" style="background-image: url('/assets/shutterstock_234372322.jpg');">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Seja um <span>Participante</span></h1>
          <p class="animated fadeInRightBig">Aprenda em qualquer lugar do mundo o que quiser</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Experimente</a>
        </div>
      </div>
      <div class="item" style="background-image: url('/assets/shutterstock_217119211.jpg');">
        <div class="caption">
          <h1 class="animated fadeInLeftBig">Ou seja um <span>Expositor</span></h1>
          <p class="animated fadeInRightBig">Ensine em qualquer lugar do mundo no horário que quiser</p>
          <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Ensine agora</a>
        </div>
      </div>
    </div>
    <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
    <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>

    <a id="tohash" href="#participante"><i class="fa fa-angle-down"></i></a>

  </div><!--/#home-slider-->
  <%= render "layouts/header"%><!--/#main-nav-->
</header><!--/#home-->

app/views/new_cap/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>newcap - Ensine e Aprenda</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="#">
</head>

<body>

  <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>

  <%= render :template => "new_cap/home"%>

  <section id="participante">
    <div class="container">
      <%= render :template => "new_cap/participante"%>
    </div>
  </section>

  <section id="expositor">
    <div class="container">
      <%= render :template => "new_cap/expositor"%>
    </div>
  </section>

  <section id="about-us" class="parallax">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="about-info wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
            <h2>Quem somos</h2>
            <p>A newcap é uma plataforma online que conecta pessoas que queiram aprender com pessoas que queiram ensinar. Criada em fevereiro de 2016 por quatro estudantes brasileiros, a newcap tem como objetivo facilitar a troca de conhecimento entre pessoas por todo o mundo. </p>
            <p>Todos podem aprender algo com o outro. Não importa se você é um ganhador do prêmio Nobel ou um estudante de graduação. Com a newcap, qualquer pessoa que queira expor sobre determinado assunto pode ensinar àqueles que estiverem interessados em aprender. </p>
            <p>Toda a intermediação é feita online em nosso site, mas os cursos são presenciais. A newcap acredita que a melhor forma de assimilar conhecimento é com interação, pois podem ser trabalhadas diferentes formas de inteligência, além de facilitar o networking. A plataforma permite também o financiamento coletivo de projetos para pessoas que não tenham condições de custear, garantindo, assim, que todos tenham acesso ao conhecimento.</p>
          </div>
        </div>
      </div>
    </div>
  </section>


<% if !logged_in? %>
  <section id="signupcontainer">
    <div id="signup"class="container">
      <div class="line">
       <div class="col-md-6 quad">
         <div class="row">
           <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp"
               data-wow-duration="1200ms" data-wow-delay="300ms">
             <h2>Registrar</h2>
             <p>Cadastre-se e faça parte da comunidade newcap!</p>
           </div>

           <%= form_for(@user) do |f| %>
               <div class="buttonHolder">
                   <%= f.text_field :nickname, :placeholder => "Nome de Usuario" %>
                   <%= f.text_field :complete_name, :placeholder =>
                       "Nome Completo" %>
                   <%= f.text_field :email, :placeholder => "E-mail" %>
                   <span style="display: block;text-align: center;font-size: 18px;">
                       Data de nascimento:
                   </span>
                   <%= f.date_field :birthday,  class: 'form-control' %>
                   <%= f.password_field :password, :placeholder => "Senha" %>
                   <%= f.password_field :password_confirmation,
                       :placeholder => "Confirmação de senha" %>
                   <%= f.check_box :terms %>
                   <%= f.label :terms, "Eu aceito os termos de serviço" %>
                   <%= f.submit "Entrar"%>
               </div>
            <% end %>
         </div>
        </div>
        <div class="col-md-6 quad">
          <div class="row">
            <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp"
                data-wow-duration="1200ms" data-wow-delay="300ms">
              <h2>Login</h2>
              <p>Faça login para acessar sua conta</p>
            </div>

            <%= form_tag sessions_path do %>
                <div class="buttonHolder">
                    <%= text_field_tag :email, nil, placeholder: 'E-mail'  %>
                    <%= password_field_tag :password, nil, placeholder: 'Senha' %>
                    <%= submit_tag "Login"%>
                    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
                    <%= label_tag :remember_me, nil %>
                    <%= link_to "Esqueci minha senha", password_resets_path %>
                </div>

          </div>
          <% end %>
        </div>

      </div>
    </div>
  </section>
<% end %>
  <section id="contact">
    <!-- <div id="google-map" class="wow fadeIn" data-latitude="-15.7942287" data-longitude="-47.8821658" data-wow-duration="1000ms" data-wow-delay="400ms"></div> -->
    <div id="contact-us" class="parallax">
      <div class="container">
        <%= render :template => "new_cap/contato"%>
      </div>
    </div>
  </section>
</body>
</html>

app/views/new_cap/participante.html.erb
<div class="row">
  <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
    <h2>Participante</h2>
    <h3>Imagine se você pudesse aprender em qualquer lugar do mundo, sem restrições...</h3>
    <h3>Escolha o que, quando e onde e faça isso!</h3>
    <p>Aprenda sobre diferentes assuntos com diferentes pessoas. Para participar dos nossos caps você não precisa ser ligado a nenhuma instituição de ensino, nem possuir certificações. É só entrar na nossa Prateleira e escolher o cap que mais se parece com você. </p>
    <p>Todos os usuários da newcap possuem track records de quantidade de caps e horas assistidas, que podem ser usados em promoções na newcap. Quanto mais você quiser aprender, melhor para você em todos os sentidos.</p>
    <p>Vamos lá, participe de um cap!</p>
  </div>
</div>
<div class="blog-posts">
  <div class="row">
    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">
      <div class="post-thumb">
        <%= image_tag("shutterstock_267954611.jpg", class: 'img-responsive')%>

      </div>
      <div class="entry-header">
        <h3><a>Escolha o cap pela área do conhecimento, formato, expositor, hora, preço ou local</a></h3>
      </div>
      <div class="entry-content">
        <p>Escolha o cap de um jeito simples e rápido. Estude materiais recomendados e faça suas sugestões ao expositor.</p>
      </div>
    </div>
    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
      <div class="post-thumb">
        <%= image_tag("shutterstock_217847221.jpg", class: 'img-responsive')%>
      </div>
      <div class="entry-header">
        <h3><a>Sinta a experiência de estudar no local que maximizará seu aprendizado</a></h3>
      </div>
      <div class="entry-content">
        <p>Aprender está ligado à experiências e conteúdo. Tenha aulas em museus, parques, em casa ou até mesmo em cafés. </p>
      </div>
    </div>
    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="800ms">
      <div class="post-thumb">
        <%= image_tag("shutterstock_234385096.jpg", class: 'img-responsive')%>

      </div>
      <div class="entry-header">
        <h3><a>Mais barato que escolas convencionais e mais social que cursos online</a></h3>
      </div>
      <div class="entry-content">
        <p>Participe de cursos, conversas, debates à sua escolha. Aproveite ao máximo essa experiência. </p>
      </div>
    </div>
  </div>
</div>