config/routes.rb
Rails.application.routes.draw do

    get 'tags/:tag', to: 'caps#index', as: :tag

    get 'caps/index'
    get 'caps/show'
    get 'caps/new'
    get 'caps/edit'

    resources :caps, param: :token do
      resources :participations
    end
    resources :password_resets
    resources :users, param: :token
    resources :searches

    resources :sessions, only: [:new, :create, :destroy]

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'user/index'
    get 'new_cap/index'
    root 'new_cap#index'

    resources :users do
        member do
            get :confirm_email
        end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessible :nickname, :complete_name, :email, :password, :terms,
        :profile_image, :birthday, :experience, :address, :latitude, :longitude,
        :city, :state, :country, :curriculum
    has_secure_password
    has_secure_token
    before_create :confirmation_token
    before_create { generate_token(:auth_token) }
    has_many :participations
    has_many :caps, dependent: :destroy
    has_many :caps, through: :participations
    geocoded_by :address

    after_validation    :geocode,
                        :on => :update,
                        :if => :address_changed?

    validates   :nickname,
                presence: true,
                uniqueness: true,
                length:{
                    minimum: 3,
                    maximum: 45
                }

    validates   :complete_name,
                format: {
                  with: /[a-zA-Z]+/
                },
                presence: true,
                length:{
                    minimum: 3,
                    maximum: 45
                }

    validates   :email,
                presence: true,
                uniqueness: true,
                format: {
                    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
                }
    validates   :password,
                :on => :create,
                length:{
                    minimum: 6,
                    maximum: 20
                },
                presence: true

    validates   :terms,
                :acceptance => true

    has_attached_file   :profile_image
    validates_attachment    :profile_image,
        content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }


    has_attached_file   :curriculum
    validates_attachment    :curriculum,
        content_type: { :content_type => %w(application/pdf
          application/msword application/vnd.openxmlformats-officedocument
            .wordprocessingml.document) }

    validates_date  :birthday,
                    on_or_after: lambda { 125.years.ago },
                    on_or_before: lambda { 18.years.ago }

    validates   :experience,
                :on => :update,
                length:{ maximum: 300 }
# Ativação do email
    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end
# Lembrar-me(para manter o usuario conectado)
    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end
# Reseta a senha do usuario e manda e-mail com instruções para redefinição da mesma
    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        save!(:validate => false)
        UserMailer.password_reset(self).deliver_now
    end

    def to_param
      token
    end
# Chave que será mandada pelo email
    private
        def confirmation_token
            if self.confirm_token.blank?
                self.confirm_token = SecureRandom.urlsafe_base64.to_s
            end
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorize, only: [:new, :create, :update, :index]
    before_action :authorize, except: [:show, :index]

    def index
        @users = User.all
    end

    def show
      @cap = Cap.new
      @joined = @user.caps
      @caps = Cap.where(:caps => { :user_id => @user.id })
    end

    def new
        @user = User.new
    end
# Metodo create irá pedir que o usuário confirme o email
    def create
        @user = User.new(user_params)
        # Caso o usuario seja salvo com os dados validos, um email sera enviado
        if @user.save
            UserMailer.registration_confirmation(@user).deliver_now
            flash[:error] = "Por favor confirme seu cadastro no email que enviamos"
            redirect_to login_url
        else
            flash[:error] = "Tente novamente! Ocorreu alguma falha no cadastro."
            render 'new'
        end
    end
# Metodo update permitira que o usuário faça a edição dos dados que achar necessario
    def update
        @user = User.find_by_token(params[:token])
        if @user.update(user_params)
            redirect_to @user
            flash[:success] = 'Perfil atualizado'
        else
            render :edit
        end
    end
# Metodo destroy exclui o usuário
    def destroy
        @user.destroy
        redirect_to users_url
        flash[:success] = 'Conta removida com sucesso.'
    end
# Método que irá verificar se o usuário confirmou o email de registro
    def confirm_email
        user = User.find_by_confirm_token(params[:id])
        if user
            user.email_activate
            flash[:success] = "Bem vindo a newcap! Sua conta foi confirmada com
            sucesso!"
            redirect_to login_url
        else
            flash[:error] = "Desculpe, o usuário não existe"
            redirect_to login_url
        end
    end

    private
        def set_user
            @user = User.find_by_token(params[:token])
        end

        def user_params
            params.require(:user).permit(:nickname, :complete_name, :email,
                :password, :password_confirmation, :terms, :profile_image,
                :birthday, :experience, :address, :latitude, :longitude,
                :city, :state, :country, :curriculum)
        end

        def authorize
            if current_user.nil?
                redirect_to login_url
                flash[:error] = "Não autorizado, por favor faça login"
            else
                if @user != current_user
                    redirect_to root_path,
                    flash[:error] = "Usuário não autorizado!"
                end
            end
        end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<!-- HTML responsavel por mostrar os erros na tentativa de cadastro
A validação é feita, e se houverem erros, ele os indicará ao usuario -->
    <% if @user.errors.any? %>
        <div style="color:red;" id="error_explanation">
            <h2>Can't sign up,
                <%= pluralize(@user.errors.count, "error", "errors") %> found
            </h2>

            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li class ="err-list"><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<% end %>

app/views/users/_profile_bar.html.erb
<div class="col-sm-2">
    <div class="profile-bar">
        <div class="profile-image">
            <%= image_tag(
                @user.profile_image_file_name.blank? ? "profile" : @user.profile_image.url, alt: "Profile image") %>
        </div>
        <div>
          <p id="user-name"><%= @user.complete_name %></p>
          <% if logged_in? && current_user = @user %>
          <div>
            <%= link_to "Editar Perfil", edit_user_path, class: "white-font" %>
          </div>
          <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/inner_header' %>
<%= render 'form' %>
<%= render 'profile_bar' %>

<div class="container" style="padding-bottom: 1em;padding-top: 1em;">
  <div class="col-sm-10 content main-content">
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#perfil">Informações principais</a></li>
      <li><a data-toggle="tab" href="#password">Alterar senha</a></li>
    </ul>

    <div id="signup" class="tab-content">
      <div id="perfil" class="tab-pane fade in active">
        <%= form_for(@user) do |f| %>
        <div class="line">
         <div class="col-md-6 quad">
          <div class="row">
            <span style="display: block;text-align: center;font-size: 18px;">
                Nome Completo:
            </span>
            <%= f.text_field :complete_name, :placeholder => "Nome Completo",
              class: 'form-control' %>
            <span style="display: block;text-align: center;font-size: 18px;">
                Experiência:
            </span>
            <%= f.text_area :experience, :placeholder => "Máximo 300 caractéres",
              class: 'form-control', rows: 8%>
            <span style="display: block;text-align: center;font-size: 18px;">
                Data de nascimento:
            </span>
            <%= f.date_field :birthday,  class: 'form-control' %>
            <span>
                Envie o seu curriculo para que outros usuários saibam mais sobre você
            </span>
            <%= f.file_field :curriculum, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-6 quad">
          <div class="row">
              <span style="display: block;text-align: center;font-size: 18px;">
                  Seu endereço:
              </span>
              <div id="locationField">
                  <%= f.text_field :address, :onfocus => "geolocate()",
                      :placeholder => "Seu Endereço", :id => 'autocomplete',
                      class: 'form-control' %>
              </div>
              <%= f.text_field :city, :placeholder => "Cidade",
                :id => 'locality', class: 'form-control', :disabled => 'true'-%>
              <%= f.text_field :state, :placeholder => "Estado",
                :id => 'administrative_area_level_1', class: 'form-control',
                :disabled => 'true'-%>
              <%= f.text_field :country, :placeholder => "Estado",
                :id => 'country', class: 'form-control', :disabled => 'true'-%>

              <span>
                  Escolha uma imagem para o seu perfil
              </span>
              <%= f.file_field :profile_image, class: 'form-control' %>

              <%= f.submit "Salvar" %>

              <input id="street_number" style="display:none;"></input>
              <input  id="route" style="display:none;"></input>
              <input  id="locality" style="display:none;"></input>
              <input id="administrative_area_level_1" style="display:none;"></input>
              <input  id="postal_code" style="display:none;"></input>
              <input id="country" style="display:none;"></input>

              <script src="javascripts/application.js"></script>
              <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDChvz7UKPFqsIuiqkmdZVGY5Nu0OUthM&signed_in=true&libraries=places&callback=initAutocomplete"
                  async defer></script>
            <% end %>
            </div>
          </div>
        </div>
      </div>

      <div id="password" class="tab-pane fade">
        <%= form_for(@user) do |f| %>
          <%= f.password_field :password, :placeholder => "Senha" %>
          <%= f.password_field :password_confirmation,
              :placeholder => "Confirmação de senha" %>
          <%= f.submit "Salvar" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/inner_header' %>
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Complete name</th>
      <th>E-mail</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.complete_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>newcap - Registrar</title>
  <%= render 'layouts/inner_header' %>
  <%= render 'users/form' %> <!--Renderiza a pagina form.html.erb-->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'
      rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="#">
</head><!--/head-->
<body>
  <section id="signup">
      <div class="row">
        <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp"
            data-wow-duration="1200ms" data-wow-delay="300ms">
          <h2>Registrar</h2>
          <p>Cadastre-se e faça parte da comunidade newcap!</p>
        </div>

        <%= form_for(@user) do |f| %>
            <div class="buttonHolder">
                <%= f.text_field :nickname, :placeholder => "Username" %>
                <%= f.text_field :complete_name, :placeholder =>
                    "Nome Completo" %>
                <%= f.text_field :email, :placeholder => "E-mail" %>
                <span style="display: block;text-align: center;font-size: 18px;">
                    Data de nascimento:
                </span>
                <%= f.date_field :birthday,  class: 'form-control' %>
                <%= f.password_field :password, :placeholder => "Senha" %>
                <%= f.password_field :password_confirmation,
                    :placeholder => "Confirmação de senha" %>
                <%= f.check_box :terms %>
                <%= f.label :terms, "Eu aceito os termos de serviço" %>
			          <%= f.submit "Entrar"%>
            </div>
		<% end %>
      </div>
  </section><!--/#signup-->
</body>
</html>

app/views/users/show.html.erb
<%= render 'layouts/inner_header' %>
<p id="notice"><%= notice %></p>
<%= render 'profile_bar' %>
<div class="container" style="padding-bottom: 1em;">
  <div class="col-sm-10 content main-content">
    <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#perfil">Perfil</a></li>
    <% if logged_in? && current_user = @user %>
    <li><a data-toggle="tab" href="#joined">Caps inscritos</a></li>
    <li><a data-toggle="tab" href="#caps">Meus Caps</a></li>
    <li><a data-toggle="tab" href="#createcap">Criar Caps</a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div id="perfil" class="tab-pane fade in active">
      <h3><%= @user.complete_name %></h3>
      <table class="table">
        <tr>
          <td><b>Usuário:</b> <%= @user.nickname %></td>
        </tr>
        <tr>
          <td><b>E-mail:</b> <%= @user.email %></td>
        </tr>
        <tr>
          <td><b>Membro desde:</b> <%= @user.created_at.strftime(" %d/%m/%Y ") %></td>
        </tr>
        <tr>

          <td><b>Aniversario:</b> <%= @user.birthday.strftime(" %d/%m/%Y ") rescue "Não informado"%></td>
        </tr>
        <tr>
          <td><b>Experiencia:</b> <%= @user.experience %></td>
        </tr>
        <% if logged_in? && current_user = @user%>
        <tr>
          <td><b>Endereço:</b> <%= @user.address %></td>
        </tr>
        <% end %>
      </table>
    </div>
    <% if logged_in? && current_user = @user %>
    <div id="createcap" class="tab-pane fade">
      <div id="signup" class="row" style="padding-top: 1em;">
        <%= form_for(@cap) do |f| %>
        <div class="line">
          <div class="col-md-6 quad">
            <div class="row">
                <%= f.text_field :title, :placeholder => "Nome do Cap",
                  class: 'form-control' %>
                <%= f.collection_select :tag_list, ActsAsTaggableOn::Tag.all.order(:name),
                  :name, :name, {:prompt => 'Selecione a area'} %>

                <span style="display: block;text-align: center;font-size: 18px;">
                    Data do inicio do Cap:
                </span>
                <%= f.date_field :start_at, class: 'form-control' %>

                <span style="display: block;text-align: center;font-size: 18px;">
                    Data do fim do Cap:
                </span>
                <%= f.date_field :end_at, class: 'form-control' %>

                <span style="display: block;text-align: center;font-size: 18px;">
                    Horário do inicio:
                </span>
                <%= f.time_select :time_start,
                  :combined => true,
                  :default => Time.now.change(:hour => 12, :min => 00),
                  :minute_interval => 15,
                  :time_separator => "",
                  :start_hour => 0,
                  :start_minute => 0,
                  :end_hour => 23,
                  :end_minute => 45
                %>
                <span style="display: block;text-align: center;font-size: 18px;">
                    Horário do fim:
                </span>
                <%= f.time_select :time_end,
                  :combined => true,
                  :default => Time.now.change(:hour => 14, :min => 00),
                  :minute_interval => 15,
                  :time_separator => "",
                  :start_hour => 0,
                  :start_minute => 0,
                  :end_hour => 23,
                  :end_minute => 45
                %>

                <span style="display: block;text-align: center;font-size: 18px;">
                    Quantidade de encontros:
                </span>
                <%= f.number_field :meetings, value: '1', class: 'form-control', min: 1 %>

                <span style="display: block;text-align: center;font-size: 18px;">
                    Observações:
                </span>
                <%= f.text_area :observations, :placeholder => "Descreva mais seu cap, facilite para as pessoas interessadas. Diga os dias da semana e detalhes sobre o local escolhido!",
                  class: 'form-control', rows: 8%>
            </div>
          </div>

          <div class="col-md-6 quad">
            <div class="row">
                <span style="display: block;text-align: center;font-size: 18px;">
                    Apresentação:
                </span>
                <%= f.text_area :area, :placeholder => "Máximo 1000 caractéres",
                  class: 'form-control', rows: 8%>
                <div id="locationField">
                    <%= f.text_field :address, :onfocus => "geolocate()",
                        :placeholder => "Endereço do Cap", :id => 'autocomplete',
                        class: 'form-control' %>
                </div>
                <%= f.text_field :city, :placeholder => "Cidade",
                  :id => 'locality', class: 'form-control', :disabled => 'true'-%>
                <%= f.text_field :state, :placeholder => "Estado",
                  :id => 'administrative_area_level_1', class: 'form-control',
                  :disabled => 'true'-%>
                  <span>
                      Escolha uma imagem para o seu cap
                  </span>
                  <%= f.file_field :cap_image, class: 'form-control' %>

                <!-- <%= f.text_field :country, :placeholder => "País",
                  :id => 'country', class: 'form-control', :disabled => 'true'-%> -->

                <%= f.submit "Criar" %>

                <input id="street_number" style="display:none;"></input>
                <input  id="route" style="display:none;"></input>
                <input  id="locality" style="display:none;"></input>
                <input id="administrative_area_level_1" style="display:none;"></input>
                <input  id="postal_code" style="display:none;"></input>
                <input id="country" style="display:none;"></input>

                <script src="javascripts/application.js"></script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDChvz7UKPFqsIuiqkmdZVGY5Nu0OUthM&signed_in=true&libraries=places&callback=initAutocomplete"
                    async defer></script>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div id="joined" class="tab-pane fade">

      <table class="table">
        <thead>
            <th>Titulo</th>
            <th>Area</th>
            <th>Data e Horario</th>
          </tr>
        </thead>
        <tbody>
          <% @joined.each do |cap| %>
            <tr>
              <td><%= cap.title %></td>
              <td><%= raw cap.tag_list.map {|tag| link_to tag, tag_path(tag)}.join(', ') %></td>
              <td><%= cap.start_at.strftime(" %d/%m/%Y") %></td>
              <td><%= link_to 'Mostrar', cap %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="caps" class="tab-pane fade">

      <table class="table">
        <thead>
            <th>Titulo</th>
            <th>Area</th>
            <th>Data e Horario</th>
          </tr>
        </thead>
        <tbody>
          <% @caps.each do |cap| %>
            <tr>
              <td><%= cap.title %></td>
              <td><%= raw cap.tag_list.map {|tag| link_to tag, tag_path(tag)}.join(', ') %></td>
              <td><%= cap.start_at.strftime(" %d/%m/%Y") %></td>
              <td><%= link_to 'Mostrar', cap %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
  </div>
</div>