config/routes.rb
Rails.application.routes.draw do

    get 'tags/:tag', to: 'caps#index', as: :tag

    get 'caps/index'
    get 'caps/show'
    get 'caps/new'
    get 'caps/edit'

    resources :caps, param: :token do
      resources :participations
    end
    resources :password_resets
    resources :users, param: :token
    resources :searches

    resources :sessions, only: [:new, :create, :destroy]

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'user/index'
    get 'new_cap/index'
    root 'new_cap#index'

    resources :users do
        member do
            get :confirm_email
        end
    end

end

app/models/cap.rb
class Cap < ActiveRecord::Base
    attr_accessible :user, :address, :title,:area, :date, :tag_list, :city,
        :state, :country, :latitude, :longitude, :cap_image, :start_at, :end_at,
        :time_start, :time_end, :meetings, :observations

    belongs_to :user
    geocoded_by :address
    acts_as_taggable
    has_secure_token
    has_many :participations
    has_many :users, through: :participations

    after_validation    :geocode,
                        :if => :address_changed?

    validates   :title,
                presence: true

    validates_date  :start_at,
                    :after => :today

    validate :end_after_start

    validate :end_after_start_time

    validates :start_at, :end_at, :time_start, :time_end, :presence => true

    validates_numericality_of   :meetings,
                presence: true,
                greater_than: 0

    validates   :observations,
                length:{
                    maximum: 500
                }

    has_attached_file   :cap_image
    validates_attachment    :cap_image,
        content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

    validates   :area,
                presence: true,
                :on => :create,
                length:{ maximum: 1000 }

  def to_param
    token
  end

  def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end
  end

  private
    def end_after_start
      return if end_at.blank? || start_at.blank?

      if end_at < start_at
        errors.add(:end_at, "Data final d eve ser após data inicial")
      end
    end

  private
    def end_after_start_time
      return if time_end.blank? || time_start.blank?

      if time_end < time_start
        errors.add(:end_at, "Horário final deve ser após data inicial")
      end
    end
end

app/controllers/caps_controller.rb
class CapsController < ApplicationController
    before_action :set_cap, only: [:show, :edit, :update, :destroy]
    before_action :authorize, except: [:show, :index]

    def index
        if params[:tag]
            @caps = Cap.tagged_with(params[:tag])
        else
            @caps = Cap.all
        end
        @caps_by_date = @caps.group_by(&:start_at)
        @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end

    def new
        @cap = Cap.new
    end

    def create
        @cap = current_user.caps.build(cap_params)
        @cap.user_id = current_user.id
        if @cap.save
            redirect_to @cap
            flash[:success] = 'Cap criado!'
        else
            render :new
        end
    end

    def show
      @users = @cap.users
    end

    def edit
    end

    def destroy
        @cap.destroy
        redirect_to caps_path
        flash[:success] = 'Cap deletado!'
    end

    private
        def set_cap
            @cap = Cap.find_by_token(params[:token])
        end

        def cap_params
            params.require(:cap).permit(:title, :area, :date, :time, :address,
                :latitude, :longitude, :tag_list, :city, :state, :country,
                :cap_image, :start_at, :end_at, :time_start, :time_end,
                :meetings, :observations)
        end

        def authorize
            if current_user.nil?
                redirect_to login_url
                flash[:error] = "Não autorizado, por favor faça login"
            else
                if @cap && @cap.user != current_user
                    redirect_to root_path,
                    flash[:error] = "Usuário não autorizado!"
                end
            end
        end
end

app/helpers/caps_helper.rb
module CapsHelper
end

app/views/caps/_form.html.erb
<%= form_for(@cap) do |f| %>
    <% if @cap.errors.any? %>
        <div style="color:red;" id="error_explanation">
            <h2>Não foi possível criar o Cap,
                <%= pluralize(@cap.errors.count, "erro", "erros") %> encontrados
            </h2>

            <ul>
                <% @cap.errors.full_messages.each do |message| %>
                    <li class ="err-list"><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<% end %>

app/views/caps/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<%= render 'layouts/inner_header' %>
<div class="container">
  <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
    <h2>Caps</h2>
    <h3>Encontre o Cap que deseja</h3>
    <h3>Procure por categorias</h3>
  </div>
</div>

<div class="container">
  <% tag_cloud ActsAsTaggableOn::Tag.all.order(:name), %w[btn] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<div class="container">
  <div id="calendar">
    <h2 id="month">
      <%= link_to "<", date: @date.prev_month %>
      <%= @date.strftime("%B %Y") %>
      <%= link_to ">", date: @date.next_month %>
    </h2>
    <%= calendar @date do |date| %>

      <%= date.day %>
      <% if @caps_by_date[date] %>
        <ul>
          <% @caps_by_date[date].each do |cap| %>
          <%= link_to cap.title, cap %>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

<%= form_tag caps_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Procurar"%>
<% end %>
<%= link_to "Busca avançada", new_search_path %>

<table class="table">
  <thead>
    <tr>
      <th>Dono</th>
      <th>Titulo</th>
      <th>Area</th>
      <th>Data e Horario</th>
      <th colspan="2"></th>

    </tr>
  </thead>

  <tbody>
    <% @caps.each do |cap| %>
      <tr>
        <td><%= cap.user.nickname %></td>
        <td><%= cap.title %></td>
        <td><%= cap.area %></td>
        <td><%= cap.start_at.strftime(" %d/%m/%Y") %></td>
        <td><%= link_to 'Show', cap %></td>
        <% if logged_in? && current_user = cap.user%>
            <td><%= link_to 'Remove', cap_path(cap), method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Participar', new_cap_participation_path(cap) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
<%= link_to 'New', new_cap_path %>
<% end %>

app/views/caps/new.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>newcap - Registrar</title>
  <%= render 'layouts/inner_header' %>
  <%= render 'form' %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'
      rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="#">
</head>
<body>
  <div id="signup" class="row" style="padding-top: 1em;">

    <%= form_for(@cap) do |f| %>
    <div class="line">
      <div class="col-md-6 quad">
        <div class="row">
            <%= f.text_field :title, :placeholder => "Nome do Cap",
              class: 'form-control' %>
            <%= f.collection_select :tag_list, ActsAsTaggableOn::Tag.all.order(:name),
              :name, :name, {:prompt => 'Selecione a area'} %>

            <span style="display: block;text-align: center;font-size: 18px;">
                Data do inicio do Cap:
            </span>
            <%= f.date_field :start_at, class: 'form-control' %>

            <span style="display: block;text-align: center;font-size: 18px;">
                Data do fim do Cap:
            </span>
            <%= f.date_field :end_at, class: 'form-control' %>

            <span style="display: block;text-align: center;font-size: 18px;">
                Horário do inicio:
            </span>
            <%= f.time_select :time_start,
              :combined => true,
              :default => Time.now.change(:hour => 12, :min => 00),
              :minute_interval => 15,
              :time_separator => "",
              :start_hour => 0,
              :start_minute => 0,
              :end_hour => 23,
              :end_minute => 45
            %>
            <span style="display: block;text-align: center;font-size: 18px;">
                Horário do fim:
            </span>
            <%= f.time_select :time_end,
              :combined => true,
              :default => Time.now.change(:hour => 14, :min => 00),
              :minute_interval => 15,
              :time_separator => "",
              :start_hour => 0,
              :start_minute => 0,
              :end_hour => 23,
              :end_minute => 45
            %>

            <span style="display: block;text-align: center;font-size: 18px;">
                Quantidade de encontros:
            </span>
            <%= f.number_field :meetings, value: '1', class: 'form-control', min: 1 %>

            <span style="display: block;text-align: center;font-size: 18px;">
                Observações:
            </span>
            <%= f.text_area :observations, :placeholder => "Descreva mais seu cap, facilite para as pessoas interessadas. Diga os dias da semana e detalhes sobre o local escolhido!",
              class: 'form-control', rows: 8%>
        </div>
      </div>

      <div class="col-md-6 quad">
        <div class="row">
            <span style="display: block;text-align: center;font-size: 18px;">
                Apresentação:
            </span>
            <%= f.text_area :area, :placeholder => "Máximo 1000 caractéres",
              class: 'form-control', rows: 8%>
            <div id="locationField">
                <%= f.text_field :address, :onfocus => "geolocate()",
                    :placeholder => "Endereço do Cap", :id => 'autocomplete',
                    class: 'form-control' %>
            </div>
            <%= f.text_field :city, :placeholder => "Cidade",
              :id => 'locality', class: 'form-control', :disabled => 'true'-%>
            <%= f.text_field :state, :placeholder => "Estado",
              :id => 'administrative_area_level_1', class: 'form-control',
              :disabled => 'true'-%>
              <span>
                  Escolha uma imagem para o seu cap
              </span>
              <%= f.file_field :cap_image, class: 'form-control' %>

            <!-- <%= f.text_field :country, :placeholder => "País",
              :id => 'country', class: 'form-control', :disabled => 'true'-%> -->

            <%= f.submit "Criar" %>

            <input id="street_number" style="display:none;"></input>
            <input  id="route" style="display:none;"></input>
            <input  id="locality" style="display:none;"></input>
            <input id="administrative_area_level_1" style="display:none;"></input>
            <input  id="postal_code" style="display:none;"></input>
            <input id="country" style="display:none;"></input>

            <script src="javascripts/application.js"></script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDChvz7UKPFqsIuiqkmdZVGY5Nu0OUthM&signed_in=true&libraries=places&callback=initAutocomplete"
                async defer></script>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</body>
</html>w

app/views/caps/show.html.erb
<%= render 'layouts/inner_header' %>
<div class="container">
<p id="notice"><%= notice %></p>
<div id="container-outer">
  <div id="container-inner">
    <%=  image_tag(
        @cap.cap_image_file_name.blank? ? "camera-outline" :
        @cap.cap_image.url, alt: @cap.title, class: "cap-img") %>
  </div>
</div>

<% if logged_in? && current_user = @cap.user %>
  <div id="signup">
    <%= form_for(@cap) do |f| %>
      <% if   @cap.cap_image_file_name.blank?%>
        <span>
            Escolha uma imagem para o seu Cap
        </span>
      <% else %>
        <span>
            Altere uma imagem para o seu Cap
        </span>
      <% end %>
        <%= f.file_field :cap_image, class: 'form-control' %>
        <%= f.submit "Salvar" %>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
    <h2><%= @cap.title %></h2>
    <h3>Apresentação</h3>
    <p><%= @cap.area %></p>
    <p>Para ser um Expositor com a newcap você não precisa ser ligado a nenhuma instituição de ensino, possuir certificações e muito menos de uma sala de aula convencional. </p>
  </div>
</div>


<p>
  <strong>Expositor:</strong>
  <%= link_to @cap.user.nickname, @cap.user %>
</p>

<p>
  <strong>Observações:</strong>
  <%= @cap.observations %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= raw @cap.tag_list.map {|tag| link_to tag, tag_path(tag)}.join(', ') %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @cap.start_at.strftime(" %d/%m/%Y") %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @cap.end_at.strftime(" %d/%m/%Y") %>
</p>

<p>
  <strong>Horario de inicio:</strong>
  <%= @cap.time_start.strftime(" %M:%S") %>
</p>

<p>
  <strong>Horario de fim:</strong>
  <%= @cap.time_end.strftime(" %M:%S") %>
</p>

<p>
  <strong>Encontros:</strong>
  <%= @cap.meetings %>
</p>

<p>
  <strong>Local do cap:</strong>
  <%= @cap.address %>
</p>
 <td><%= link_to 'Participar', new_cap_participation_path(@cap) %></td>

<table class="table">
  <h1>Participantes</h1>
  <thead>
      <th>Participante</th>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.complete_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>Distancia do cap:</strong>
  <%= @cap.distance_to([current_user.latitude, current_user.longitude]) %>
</p>
<%= content_tag(:div, "", id: "google-map", class: "wow fadeIn", "data-latitude"=> @cap.latitude, "data-longitude"=> @cap.longitude, "data-wow-duration"=>"1000ms", "data-wow-delay"=>"400ms") %>
</div>
<!-- <div id="google-map" class="wow fadeIn" data-latitude="-15.7942287" data-longitude="-47.8821658" data-wow-duration="1000ms" data-wow-delay="400ms"></div> -->