config/routes.rb
Rails.application.routes.draw do

    get 'tags/:tag', to: 'caps#index', as: :tag

    get 'caps/index'
    get 'caps/show'
    get 'caps/new'
    get 'caps/edit'

    resources :caps, param: :token do
      resources :participations
    end
    resources :password_resets
    resources :users, param: :token
    resources :searches

    resources :sessions, only: [:new, :create, :destroy]

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'user/index'
    get 'new_cap/index'
    root 'new_cap#index'

    resources :users do
        member do
            get :confirm_email
        end
    end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
    <div class="container text-center">
      <div class="footer-logo">
        <a><h1><%= link_to "newcap", root_path, :class => "white-font" %></h1></a>
      </div>
      <div class="social-icons">
        <ul>
          <li><a class="envelope" href="#contact"><i class="fa fa-envelope"></i></a></li>
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p>&copy; newcap</p>
        </div>
        <div class="col-sm-6">
          <p class="pull-right">Designed by <%= link_to "newcap", root_path %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
  <div class="main-nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="footer-logo">
          <a><h1><%= link_to "newcap", root_path, :class => "white-font" %></h1></a>
        </div>

      </div>
      <div id="menu"class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a class="ativo" href="#home">Home</a></li>
          <li><a href="#participante">Participante</a></li>
          <li><a href="#expositor">Expositor</a></li>
          <li><a href="#about-us">Quem somos</a></li>
          <% if logged_in? %>
              <li><a href="#contact">Contato</a></li>
              <li><%= link_to current_user.complete_name, current_user %></li>
              <li><%= link_to "Log Out", logout_path %></li>

          <% else %>
              <li><a href="#signupcontainer">Entrar</a></li>
              <li><a href="#contact">Contato</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <% flash.each do |key, value| %>
      <%= content_tag(:div, class: "alert alert-#{key}") do %>
          <p><%= value %></p>
      <% end %>
  <% end %>

app/views/layouts/_inner_header.html.erb
<div class="main-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="footer-logo">
        <a><h1><%= link_to "newcap", root_path, :class => "white-font" %></h1></a>
      </div>

    </div>
    <div id="menu"class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Caps", caps_path %></li>
        <% if logged_in? %>
            <li><%= link_to current_user.complete_name, current_user %></li>
            <li><%= link_to "Log Out", logout_path %></li>

        <% else %>
            <li><%= link_to 'Registrar', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% flash.each do |key, value| %>
    <%= content_tag(:div, class: "alert alert-#{key}") do %>
        <p><%= value %></p>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>newcap</title>
    <%= stylesheet_link_tag 'application', 'bootstrap.min', 'animate.min',
    'font-awesome.min', 'lightbox', 'main', 'responsive', media: 'all',
    'data-turbolinks-track' => true %>
    <link id="css-preset" href="css/presets/preset1.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track', 'jquery',
    'bootstrap.min', 'jquery.inview.min', 'wow.min', 'mousescroll',
    'smoothscroll', 'jquery.countTo', 'lightbox.min', 'btnSignUp',
    'main' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

    <%= yield %>
    <%= render 'layouts/footer' %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDChvz7UKPFqsIuiqkmdZVGY5Nu0OUthM&signed_in=true&libraries=places&callback=initAutocomplete"
      async defer></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
</body>
</html>

app/views/layouts/password_reset.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
      <p>Hi <%= @user.complete_name %>,</p>
      <p>
          To reset your password, click the URL below.
      </p>
      <p><%= edit_password_reset_url(@user.password_reset_token) %></p>

  </body>
</html>

app/views/layouts/registration_confirmation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
      <p>Hi <%= @user.complete_name %>,</p>
      <p>
          Thanks for registering in New Cap!
          Please, confirm your registration click the URL below.
      </p>
      <p><%= confirm_email_user_url(@user.confirm_token) %></p>

  </body>
</html>

app/views/layouts/registration_confirmation.text.erb
<!-- Esse é o email que a pessoa receberá para a confirmação -->
Hi <%= @user.name %>,

Thanks for registering in New Cap!
Please, confirm your registration click the URL below.

<%= confirm_email_user_url(@user.confirm_token) %>